### ISSUE TITLE
Each time minimize Terminal UWP window gray rectangle stay in corner

### ISSUE THREAD

**Issue by FadeMind** [MicaForEveryone/MicaForEveryone#121] opened 2022-08-21 19:57 UTC
After minimize Terminal Window on left side corner rectangle left 

MicaForEveryone work

![20220821-1661111418](https://user-images.githubusercontent.com/9846948/185808534-760388f3-7c88-43de-b2f4-729cd9d0d696.png)
![20220821-1661111427](https://user-images.githubusercontent.com/9846948/185808536-9ce341aa-673d-47f6-9957-4798bd7fe5b7.png)

MicaForEveryone turn off

![20220821-1661111446](https://user-images.githubusercontent.com/9846948/185808537-c9bf5130-8bff-4610-9360-64d19bb3f190.png)
![20220821-1661111455](https://user-images.githubusercontent.com/9846948/185808539-2bf8b10d-6b98-43b3-b2d8-d22f74be496d.png)

Toobar style via StartAllBack explorer tweak. 
I excluded this app. 

I have default settings for `ConsoleWindowClass`

**Comment by xmine64** [comment] 2022-08-21 20:15
Duplicate of #120
Already taken care of by @dongle-the-gadget

**Closed** 2022-08-21 20:15 UTC
