### ISSUE TITLE
.NET Core Depreciation, opt for .NET 7+

### ISSUE THREAD

**Issue by AskaLangly** [MicaForEveryone/MicaForEveryone#352] opened 2023-09-04 04:57 UTC
Instead of opting for the installer, I went with the ZIP. Seeing it needs .NET Core, I went to its download page, just to see that it's apparently end-of-life. So, I went to install .NET 7, just to see MFE not wanting it. Is it alright to ask to move to a supported .NET release?

![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/6183728/4ab8b6d2-9658-4dcf-96f9-bf010cd64304)

**Comment by dongle-the-gadget** [comment] 2023-09-04 07:32
Duplicate of #209.

**Closed** 2023-09-05 23:20 UTC
Labels: duplicate
