### ISSUE TITLE
Don't have "remove rule" button, when I what remove a rule, I have to edit config file

### ISSUE THREAD

**Issue by chuck00000** [MicaForEveryone/MicaForEveryone#251] opened 2023-02-12 11:24 UTC
![Screenshot (11)](https://user-images.githubusercontent.com/98159699/218308001-551f3669-f592-472c-985c-ddb18347cecf.png)

**Comment by dongle-the-gadget** [comment] 2023-02-12 11:28
Duplicate of #.225

**Closed by dongle-the-gadget** 2023-02-12 11:28 UTC
