### ISSUE TITLE
Custom Colour Themes

### ISSUE THREAD

**Issue by kran27** [MicaForEveryone/MicaForEveryone#188] opened 2022-11-27 01:56 UTC
Currently the only options for Caption/Title bar colour are related to the Light/Dark theme in windows.

Using DWMAPI, you can modify the title bar background colour, window border colour, and caption text colour, using
`DWMWA_BORDER_COLOR` (`34`), `DWMWA_CAPTION_COLOR` (`35`), and `DWMWA_TEXT_COLOR` (`36`) respectively.

Everything other than `DWMWA_BORDER_COLOR` is already implemented.

Each of these takes a [COLORREF](https://learn.microsoft.com/en-us/windows/win32/gdi/colorref) value.

Not confident in my C# abilities to implement this into an already existing program of which I know nothing of the inner workings, but I hope this post will at least give enough info to get it implemented, if anyone knowledgeable enough is interested.

**Comment by dongle-the-gadget** [comment] 2022-11-27 02:27
Two notes to point out:
1. This API is only compatible with Windows 11.
2. This API isn't compatible with backdrop types.

**Comment by Zinvoke** [comment] 2022-12-22 20:52
![rHxPbVCJ5S](https://user-images.githubusercontent.com/84819317/209223509-83dcd9e2-cd8d-4f46-b91a-5b4b804adc47.png)


> 2\. This API isn't compatible with backdrop types.

Actually It works with backdrop types I implemented window border functionality in my bar i'm working on and it's just fine

**Comment by kran27** [comment] 2022-12-25 22:07
yep, only `DWMWA_CAPTION_COLOR` is incompatible, because it's changing the same thing as `DWM_SYSTEMBACKDROP_TYPE` border and text colour are adjacent, and will work with either.

**Comment by Dhyfer1** [comment] 2023-01-08 02:15
@Zinvoke Out of curiosity, the bars with information that appear at the top of your screenshot, what app do you use for that?

**Comment by kran27** [comment] 2023-01-08 02:37
ShareX if i'm not mistaken

**Comment by Dhyfer1** [comment] 2023-01-08 02:47
@kran27 hmmm, I don't think so. I think he's using [Polybar](https://github.com/polybar/polybar), or maybe some custom theme. 🤔

**Comment by xmine64** [comment] 2023-07-02 22:24
This should be duplicate of #145, the feature is implemented as #259 and will get shipped in a future release.

**Closed by xmine64** 2023-07-02 22:24 UTC
Labels: enhancement
