### ISSUE TITLE
Pressing F11 in Explorer resets its material to default

### ISSUE THREAD

**Issue by ThePhantomOfTheOpera69** [MicaForEveryone/MicaForEveryone#69] opened 2022-05-16 09:33 UTC

**Comment by dongle-the-gadget** [comment] 2022-05-16 10:31
Can you send me repro steps or a video demonstrating the bug? I'm afraid I can't replicate this bug.

**Comment by ThePhantomOfTheOpera69** [comment] 2022-05-16 11:29
I just opened file explorer, pressed F11 to enter the full-screen view mode, and pressed it again to exit it.

**Comment by dongle-the-gadget** [comment] 2022-05-16 11:31
I can replicate this. What I think is happening is that Explorer is changing its DWM attributes when you put it into full screen and exit out of it.

**Comment by dongle-the-gadget** [comment] 2022-05-16 11:33
One obvious solution is to put a timer and repeatedly changing the DWM attributes, however this seems inefficient.
Another solution is to hook into processes and monitor DWM attribute changes, however this method is quite unstable and requires native code, which MFE cannot do at this moment as it is using managed code.

**Comment by dongle-the-gadget** [comment] 2022-05-16 11:56
Also one thing, is F11 a supported mode in Windows 11 Explorer?

**Comment by xmine64** [comment] 2022-05-18 20:59
it is, i'm not using ep_patcher

**Comment by dongle-the-gadget** [comment] 2022-05-19 01:41
I don't see an option to do full screen in Explorer, might just be a legacy from the IE era?

**Comment by Yarrio69** [comment] 2022-05-20 20:39
It also happens when resizing/maximizing the Explorer window.

**Comment by dongle-the-gadget** [comment] 2022-05-21 01:23
> It also happens when resizing/maximizing the Explorer window.

I can't reproduce this.

**Comment by ThePhantomOfTheOpera69** [comment] 2022-05-21 04:08
It happens when resizing/maximising if "Extend Frame into Client Area" or "Blur Behind" are enabled/

**Comment by hedhehd** [comment] 2022-05-21 17:18
Yes I installed black.msstyle on Rectify11 server and from mica, it turns to arcylic.

**Comment by hedhehd** [comment] 2022-05-21 17:20
After minimizing/maximizing or unfocusing, this happens

**Comment by xmine64** [comment] 2022-05-23 14:29
It seems a correct and legal bug report to me, well I didn't try to reproduce it, but as MFE only applies rules on windows when they get opened, if they change their backdrop during runtime MFE won't reapply rule. Maybe Explorer changes backdrop type when you press F11 so this happens. Btw I won't try to fix it, it may cause poor performance.

> It might be the case that Rectify11 attempts to make it use extend frame, which is an unsupported scenario.

msstyle is capable to do that?

**Comment by dongle-the-gadget** [comment] 2022-05-23 14:30
Actually, that is just my speculation.

**Comment by dongle-the-gadget** [comment] 2022-05-23 14:38
> > Actually, that is just my speculation.
> 
> Me too, I think msstyle is just a collection of RC resources and there's no code to attempt to extend frame, but it may be possible I'm not sure about it.

Maybe check with ilovepcs?

**Comment by hedhehd** [comment] 2022-05-24 11:57
> It seems a correct and legal bug report to me, well I didn't try to reproduce it, but as MFE only applies rules on windows when they get opened, if they change their backdrop during runtime MFE won't reapply rule. Maybe Explorer changes backdrop type when you press F11 so this happens. Btw I won't try to fix it, it may cause poor performance.

How about you make an option to enable that feature so that people don't have to deal with poor performance except for me.

**Comment by xmine64** [comment] 2022-05-24 12:28
> How about you make an option to enable that feature so that people don't have to deal with poor performance except for me.

what feature? Enumerating all open windows and applying rules to them every moment? That's not good really.

**Comment by ashergz** [comment] 2022-05-27 02:50
> > How about you make an option to enable that feature so that people don't have to deal with poor performance except for me.
> 
> what feature? Enumerating all open windows and applying rules to them every moment? That's not good really. It's even not a feature.

Maybe just reapply the rule every time an explorer window comes back into focus. Sounds doable no?

**Comment by dongle-the-gadget** [comment] 2022-05-27 03:15
> Maybe just reapply the rule every time an explorer window comes back into focus. Sounds doable no?

Explorer is a whole class of breakage when it comes to both Extend + Backdrops.

**Comment by rounk-ctrl** [comment] 2022-08-03 18:41
![image](https://user-images.githubusercontent.com/70931017/182685004-844809a6-ba15-4c85-b23b-b1bf1308a5e8.png)
fixed

**Comment by xmine64** [comment] 2022-08-03 21:39
Close this issue if it's not reproducible on updated builds. Btw I'd close it even if it's still reproducible.

**Comment by dongle-the-gadget** [comment] 2022-08-04 09:34
Yeah, looks like it is fixed in 25174 now.

**Closed** 2022-09-11 05:32 UTC
Labels: third-party
