### ISSUE TITLE
MicaForEveryone failing to launch + Temporary Solution

### ISSUE THREAD

**Issue by DabiaTheNord** [MicaForEveryone/MicaForEveryone#104] opened 2022-07-28 08:17 UTC
MicaForEveryone fails to launch with the .exe release, and the signature has expired on the .msixbundle version, therefore leaving no way to install the app until an update is pushed.

If you desperately need to install MicaForEveryone, I have a temporary solution, although it's kind of chunky.

### Temporary Solution
1. Enable Developer mode in Windows Settings  >  Privacy & Security  >  For Developers  >  Developer Mode
2. Download [MicaForEveryone-x64-Release.msixbundle](https://github.com/MicaForEveryone/MicaForEveryone/releases/download/v1.1.0.5/MicaForEveryone-x64-Release.msixbundle)
3. Rename the MicaForEveryone-x64-Release.msixbundle extension to .zip
4. Extract the .zip file and open it
5. Drag MicaForEveryone.Package_1.1.0.0_x64.appx (hint: the 44mb file) to your Downloads folder (or drag it to `C:\Program Files (x86)\Mica For Everyone` if you plan to Mica for Everyone long-term)
6. Rename the MicaForEveryone.Package_1.1.0.0_x64.appx extension to .zip
7. Open the .zip file, or extract it
8. Right-click and press 'Open in Terminal'
9. Copy and paste this into the PowerShell command line:
```Add-AppxPackage -Register .\AppxManifest.xml```
10. You're done! Check in the Start menu for Mica For Everyone and it should appear. If it still doesn't launch, try running it as administrator.

Hope this helps! ^MG

(Edit 8/29/22 3:48 pm est: rewrote #5 and #9)

**Comment by xmine64** [comment] 2022-07-28 09:22
I don't recommend this solution. Exe release and msix's signature should be fine.

**Comment by KrzysiuWojcik** [comment] 2022-07-28 12:44
thanks, it worked

**Comment by Dandyboiii** [comment] 2022-07-28 21:36
> I don't recommend this solution. Exe release and msix's signature should be fine.

Hello [@xmine64](https://github.com/xmine64), the .exe release is missing vital .dll's that result in the .exe failing to launch, and the .msix/msixbundle release results in the following error when attempting to launch:

    This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to 
    obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the 
    app package must be verified (0x800B010A)

This is meant to be a temporary solution until the releases are fixed, I wouldn't suggest using this version long-term.
^MG

**Comment by dongle-the-gadget** [comment] 2022-07-29 03:58
@Dandyboiii that just means you haven't installed the root certificate, which is necessary.

**Comment by Dandyboiii** [comment] 2022-07-29 06:06
Hello [@dongle-the-gadget](https://github.com/dongle-the-gadget), in a previous installation of Mica for Everyone on the same machine, a predefined root certificate was not required, and it just worked out the box. I used the .msixbundle version and it worked as intended. I attempted to generate a self-signed root certificate but it still failed to launch.

**Comment by dongle-the-gadget** [comment] 2022-07-29 06:07
The previous certificate expired I believe? We replaced it with a newer one in some version.

**Comment by xmine64** [comment] 2022-07-29 07:56
> The previous certificate expired I believe

I lost my private key, that's why I generated a new one.

**Comment by dongle-the-gadget** [comment] 2022-07-29 08:58
Oh smh

**Comment by nonetrix** [comment] 2022-07-30 01:26
>Drag MicaForEveryone.Package_1.1.0.0_x64.appx to your main folder

Where is this main folder? Am I having a brain fart?
![Screenshot 2022-07-29 202616](https://user-images.githubusercontent.com/45698918/181865035-5e8d2a7b-55f0-4b61-9049-df6ddb6e91f3.png)

**Comment by Dandyboiii** [comment] 2022-07-30 04:02
Hello [@](https://github.com/), in your case, you'd be dragging `MicaForEveryone.Package_1.0.0.0_x64.appx` to your Downloads, then repeating the process you did with `MicaForEveryone-x64-Release` to the new folder. I'll edit the main issue so that it's easier to understand, my bad!

**Comment by ahrysicos** [comment] 2022-08-29 13:10
I can't even get this temporary workaround to work for me unfortunately :( The exe just lingers in the background after being opened, but I see no GUI appear or anything. When trying to do the whole "add app package" thing I get this:

'Add-AppxPackage' is not recognized as an internal or external command, operable program or batch file.

**Comment by ahrysicos** [comment] 2022-08-30 04:18
Oh whoops. Yeah. I was using CMD. With PowerShell, the installation worked fine. But I have the same issue still. The program doesn't appear after opening but is supposedly running in the background :(

**Comment by dongle-the-gadget** [comment] 2022-08-30 04:22
Did you see the tray icon?

**Comment by ahrysicos** [comment] 2022-08-30 04:35
Making slow progress. It appears in the system tray but comes up with this error and closes:

Error in Initializing application

System.IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by xmine64** [comment] 2022-09-01 20:31
I close this as a duplicate of #92

**Closed by xmine64** 2022-09-01 20:31 UTC
Labels: duplicate

**Comment by DabiaTheNord** [comment] 2022-09-02 00:27
The issue was not resolved

**Comment by nonetrix** [comment] 2022-09-02 23:43
> The issue was not resolved

See 

> I close this as a duplicate of #92
