### ISSUE TITLE
is it possible to make MFE not show up in system tray

### ISSUE THREAD

**Issue by baby170303** [MicaForEveryone/MicaForEveryone#192] opened 2022-12-04 03:40 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xmine64** [comment] 2022-12-04 19:54
Duplicate of #56 and #135

**Closed by xmine64** 2022-12-04 19:54 UTC
Labels: enhancement
