### ISSUE TITLE
Changing corner size to rounded or slightly rounded causes artifacting when using the terminal app.

### ISSUE THREAD

**Issue by shahiljain** [MicaForEveryone/MicaForEveryone#115] opened 2022-08-12 14:18 UTC
### Description
---
Using rounded or slightly rounded option makes a small translucent object appear in the top left corner of the screen. Even if I create an exception for the Terminal App.
Minimizing Terminal or switching desktops removes it.

### Version Info
---
Windows: 21H2

Mica For Everyone: 1.1.0.5 (I downloaded the latest release but the app still reports 1.1.0.0)

### Images
---
![image](https://user-images.githubusercontent.com/75173792/184371484-2a8657f8-3de4-443d-afc5-a1b35f591b58.png)
Screenshot without exception.

![12-08-22 230](https://user-images.githubusercontent.com/75173792/184371692-0b38efa8-30da-4e71-939b-83296fdd3e4c.jpg)
Screenshot with exception.

![12-08-22 251](https://user-images.githubusercontent.com/75173792/184371706-7d4eb9a0-bcb5-4f5b-8653-6f4d41d8444d.jpg)
Slightly Rounded

![12-08-22 784](https://user-images.githubusercontent.com/75173792/184371707-55b42b8b-d52a-47ed-8353-2f4c937ce470.jpg)
Rounded

### Steps To Reproduce
---
1. Set corners to slightly rounded/rounded.
2. Open Terminal.

**Comment by xmine64** [comment] 2022-08-12 14:27
It's not related to MFE, it's a bug caused by Desktop Window Manager or Windows Terminal. Can't be fixed by us.

**Closed** 2022-08-12 14:27 UTC
