### ISSUE TITLE
Is this app cause xbox game bar background not transparent?

### ISSUE THREAD

**Issue by chuck00000** [MicaForEveryone/MicaForEveryone#111] opened 2022-08-06 01:53 UTC
![{5EA97F30-4B6A-486D-8CAB-57B996DC81A7}](https://user-images.githubusercontent.com/98159699/183229018-14620740-2f75-49ac-99c0-3158e6f58c7c.png)

**Comment by dongle-the-gadget** [comment] 2022-08-06 05:28
Duplicate of #76.

**Closed by dongle-the-gadget** 2022-08-06 05:28 UTC
