### ISSUE TITLE
Non-trivial Windows 11 and non-trivial error when building project...

### ISSUE THREAD

**Issue by unit-404** [MicaForEveryone/MicaForEveryone#423] opened 2024-04-12 03:22 UTC
### In addition to title: 
Common in build error log:
```log
GENERATEPROJECTPRIFILE : error : PRI175: 0xdef00502 - Processing Resources
GENERATEPROJECTPRIFILE : error : PRI224: 0xdef00502 - root node not found.
```

### Description

- [x] This is not about other apps being displayed weird or etc.
- [x] This is not about rendering issues that caused by a bug in the Windows.
- [x] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
- [x] I've checked other issues and this is not a duplicate.

**Describe the bug**
> A clear and concise description of what the bug is.

I can't even build a project from source. It gives some non-trivial error (apparently my Windows version or configuration is also too non-trivial). And I unfortunately can't figure out what's wrong. 

**To Reproduce**
> Steps to reproduce the behavior (for me):

0. Cloned repository with `--recursive` (as I know) into `C:/MicaForEveryone`
1. Just opened `.sln` project (by `Visual Studio 2022 Community Preview`)
2. Tried to just build `Release` with `x64` configuration
3. Got VS error from `MicaForEveryone.UI (Universal Windows)`

Note: *my configuration or version of Windows or system may to be non-trivial...*

**Expected behavior**

🤷🏼‍♀️ Successfully built project. 🤷🏼‍♀️

**Screenshots**
> If applicable, add screenshots to help explain your problem.

No sense, I just give logs in context.

**Windows Version**
> E.g. Windows 10 build 19042, Windows 11 Build 22000, Windows 11 Build 25217 Insider Dev Channel, ...
- `Windows 11 Pro` (`23H2`, `22631.3447`) with `Rectify 11` (build from sources), `StartAllBack` and n&leSoft `Shell`.
- But planned to reinstall or upgrade Windows 11 into Dev or Canary channel (24H1 or beyond). 

**Additional context**
> Add any other context about the problem here.

```log
Rebuild started at 03:12...
Restored C:\MicaForEveryone\MicaForEveryone.Win32\MicaForEveryone.Win32.csproj (in 118 ms).
Restored C:\MicaForEveryone\MicaForEveryone.Core\MicaForEveryone.Core.csproj (in 140 ms).
Restored C:\MicaForEveryone\MicaForEveryone\MicaForEveryone.csproj (in 192 ms).
Restored C:\MicaForEveryone\MicaForEveryone.UI\MicaForEveryone.UI.csproj (in 235 ms).
Restored C:\MicaForEveryone\MicaForEveryone.Package\MicaForEveryone.Package.wapproj (in 304 ms).
1>------ Rebuild All started: Project: MicaForEveryone.Win32, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>MicaForEveryone.Win32 -> C:\MicaForEveryone\MicaForEveryone.Win32\bin\Release\netstandard2.0\MicaForEveryone.Win32.dll
1>C:\MicaForEveryone\MicaForEveryone.Win32\Window.cs(424,30,424,42): warning CS8622: Nullability of reference types in type of parameter 'sender' of 'void ForEachChild(object sender, WindowEnumeratorEventArgs args)' doesn't match the target delegate 'EventHandler<Window.WindowEnumeratorEventArgs>' (possibly because of nullability attributes).
1>C:\MicaForEveryone\MicaForEveryone.Win32\Window.cs(426,30,426,42): warning CS8622: Nullability of reference types in type of parameter 'sender' of 'void ForEachChild(object sender, WindowEnumeratorEventArgs args)' doesn't match the target delegate 'EventHandler<Window.WindowEnumeratorEventArgs>' (possibly because of nullability attributes).
1>MicaForEveryone.Win32 -> C:\MicaForEveryone\MicaForEveryone.Win32\bin\Release\net6.0-windows\MicaForEveryone.Win32.dll
1>Done building project "MicaForEveryone.Win32.csproj".
2>------ Rebuild All started: Project: MicaForEveryone.Core, Configuration: Release Any CPU ------
2>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
2>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warning : Microsoft.Extensions.DependencyInjection 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
2>Done building project "MicaForEveryone.Core.csproj".
2>C:\MicaForEveryone\MicaForEveryone.Core\Ui\Models\RulePaneItem.cs(19,26,19,32): warning CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes).
2>C:\MicaForEveryone\MicaForEveryone.Core\Services\RuleService.cs(43,33,43,49): warning CS8622: Nullability of reference types in type of parameter 'sender' of 'void RuleService.WinEvent_Handler(object sender, WindowOpenedEventArgs args)' doesn't match the target delegate 'EventHandler<WindowOpenedEventArgs>' (possibly because of nullability attributes).
2>C:\MicaForEveryone\MicaForEveryone.Core\Services\SettingsService.cs(158,32,158,37): warning CS0168: The variable 'error' is declared but never used
2>MicaForEveryone.Core -> C:\MicaForEveryone\MicaForEveryone.Core\bin\Release\netcoreapp3.1\MicaForEveryone.Core.dll
2>Done building project "MicaForEveryone.Core.csproj".
2>C:\MicaForEveryone\MicaForEveryone.Core\Services\SettingsService.cs(158,32,158,37): warning CS0168: The variable 'error' is declared but never used
2>MicaForEveryone.Core -> C:\MicaForEveryone\MicaForEveryone.Core\bin\Release\netstandard2.0\MicaForEveryone.Core.dll
2>Done building project "MicaForEveryone.Core.csproj".
3>------ Rebuild All started: Project: MicaForEveryone.UI, Configuration: Release x64 ------
3>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
3>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warning : Microsoft.Extensions.DependencyInjection 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(291,37,291,85): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(481,49,481,97): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(482,54,482,102): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(833,20,833,32): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(833,20,833,32): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version.get' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,13,838,25): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,13,838,25): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version.set' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,29,838,77): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(843,20,843,44): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(843,20,843,44): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources.get' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(848,13,848,37): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources' is for evaluation purposes only and is subject to change or removal in future updates.
3>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(848,13,848,37): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources.set' is for evaluation purposes only and is subject to change or removal in future updates.
3>  MicaForEveryone.UI -> C:\MicaForEveryone\MicaForEveryone.UI\bin\x64\Release\MicaForEveryone.UI.exe
3>GENERATEPROJECTPRIFILE : error : PRI175: 0xdef00502 - Processing Resources
3>GENERATEPROJECTPRIFILE : error : PRI224: 0xdef00502 - root node not found.
4>------ Rebuild All started: Project: MicaForEveryone, Configuration: Release x64 ------
4>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
4>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warning : Microsoft.Extensions.DependencyInjection 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
4>C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(32,5): warning NETSDK1138: The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
4>C:\MicaForEveryone\MicaForEveryone\MicaForEveryone.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.VCRTForwarders.140 1.1.0, Microsoft.VCRTForwarders.140 1.0.6.
4>MicaForEveryone.UI -> C:\MicaForEveryone\MicaForEveryone.UI\bin\x64\Release\MicaForEveryone.UI.exe
4>GENERATEPROJECTPRIFILE : error : PRI175: 0xdef00502 - Processing Resources
4>GENERATEPROJECTPRIFILE : error : PRI224: 0xdef00502 - root node not found.
4>Done building project "MicaForEveryone.UI.csproj" -- FAILED.
4>Done building project "MicaForEveryone.csproj" -- FAILED.
5>------ Rebuild All started: Project: MicaForEveryone.Package, Configuration: Release x64 ------
5>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
5>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warning : Microsoft.Extensions.DependencyInjection 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
5>Done building project "MicaForEveryone.csproj".
5>C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(32,5): warning NETSDK1138: The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
5>C:\MicaForEveryone\MicaForEveryone\MicaForEveryone.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.VCRTForwarders.140 1.1.0, Microsoft.VCRTForwarders.140 1.0.6.
5>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
5>C:\Users\User\.nuget\packages\microsoft.extensions.dependencyinjection\8.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warning : Microsoft.Extensions.DependencyInjection 8.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
5>Done building project "MicaForEveryone.Core.csproj".
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(291,37,291,85): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(481,49,481,97): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(482,54,482,102): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(833,20,833,32): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(833,20,833,32): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version.get' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,13,838,25): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,13,838,25): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.Version.set' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(838,29,838,77): warning CS8305: 'Microsoft.UI.Xaml.Controls.StylesVersion' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(843,20,843,44): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(843,20,843,44): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources.get' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(848,13,848,37): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources' is for evaluation purposes only and is subject to change or removal in future updates.
5>C:\MicaForEveryone\MicaForEveryone.UI\obj\x64\Release\XamlTypeInfo.g.cs(848,13,848,37): warning CS8305: 'Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources.set' is for evaluation purposes only and is subject to change or removal in future updates.
5>MicaForEveryone.UI -> C:\MicaForEveryone\MicaForEveryone.UI\bin\x64\Release\MicaForEveryone.UI.exe
5>GENERATEPROJECTPRIFILE : error : PRI175: 0xdef00502 - Processing Resources
5>GENERATEPROJECTPRIFILE : error : PRI224: 0xdef00502 - root node not found.
5>Done building project "MicaForEveryone.UI.csproj" -- FAILED.
5>Done building project "MicaForEveryone.csproj" -- FAILED.
========== Rebuild All: 2 succeeded, 3 failed, 0 skipped ==========
========== Rebuild completed at 03:12 and took 22.051 seconds ==========
```

**Comment by dongle-the-gadget** [comment] 2024-08-20 15:44
Hi, sorry for the late reply.

The issue was caused by a bad PR which broke the build system. This happened on the CI as well when I was trying to fix another issue.

Anyway, this should be fixed now that the bad PR has been reverted.

cc @WinExperiments, your Arabic translation PR caused the build failure. Mind investigating?

**Closed by dongle-the-gadget** 2024-08-20 15:44 UTC
Labels: bug
