### ISSUE TITLE
The App does not launch due to a missing dll

### ISSUE THREAD

**Issue by piee-kun** [MicaForEveryone/MicaForEveryone#92] opened 2022-06-29 19:31 UTC
Eventvwr shows details as follows :
```
Description: A .NET Core application failed.
Application: MicaForEveryone.exe
Path: C:\Users\Pie\AppData\Local\Programs\Mica For Everyone\MicaForEveryone.exe
Message: Error:
  An assembly specified in the application dependencies manifest (MicaForEveryone.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'
```

**Comment by dongle-the-gadget** [comment] 2022-06-30 04:22
Another runtimes folder issue.

**Comment by xmine64** [comment] 2022-06-30 12:42
> Another runtimes folder issue.

Yep, I deleted some files that I thought they're useless but seems not.

**Comment by dongle-the-gadget** [comment] 2022-06-30 14:38
Well looks like you will learn a lesson today: Don’t delete anything .NET gives as build output 😉.

**Comment by Hamaad-Siddiqui** [comment] 2022-07-03 08:28
Facing the same issue, is there a solution for this?
OS: W11 - 22621.160

**Comment by xmine64** [comment] 2022-07-03 09:57
> Facing the same issue, is there a solution for this?

It's a build issue, my fault. I'll fix it on next release. There'll be a new release soon.

**Comment by xmine64** [comment] 2022-07-03 10:01
For now, use MSIX version or extract this to `runtimes` folder.
[runtimes.zip](https://github.com/MicaForEveryone/MicaForEveryone/files/9034493/runtimes.zip)

**Comment by richmondb** [comment] 2022-07-09 12:43
i have this issue too

**Comment by dongle-the-gadget** [comment] 2022-07-09 12:44
It’s a pretty common problem actually, but I’m unsure what would cause this. Maybe @xmine64 would know?

**Comment by xmine64** [comment] 2022-07-09 13:44
> It’s a pretty common problem actually, but I’m unsure what would cause this. 

I already told you, I deleted some files from runtimes folder, I thought they're useless because MFE was working without them on my PC.

**Comment by makazeu** [comment] 2022-07-10 00:18
The installer version has this issue.

**Comment by xmine64** [comment] 2022-07-10 02:46
> The installer version has this issue.

Sure I made the installer from zip file, just to put it on winget, actually that's why I waited for next release instead of fixing it immediately, updating it on winget requires some work that I'd do it only for each release.

**Comment by xmine64** [comment] 2022-07-10 02:47
Btw next release is ready I just have to release them.

**Comment by d5aqoep** [comment] 2022-07-16 05:41
Latest release also has the same problem. Devs don't test their apps? Also I am unable to install msix. I can't find any certificate to import either. After 10 mins I give up.

**Comment by dongle-the-gadget** [comment] 2022-07-16 06:07
Releases are tested, however there are a lot of configuration differences between our dev machines and yours. Trying to replicate the user environment would require us to spin up a clean VM.

Regarding the certificate issue, right click the MSIX file and there should be a "digital signature" tab in the Properties window where you can retrieve certificate information and install one.

**Comment by dongle-the-gadget** [comment] 2022-07-16 06:08
P.S. @xmine64 can you remove the PFX from the repo? It's very insecure have a PFX in the repo.

**Comment by dongle-the-gadget** [comment] 2022-07-16 06:09
The `runtimes` issue has been plaguing MFE since release 0.3 I believe.

**Comment by xmine64** [comment] 2022-07-16 06:17
> It's very insecure have a PFX in the repo.

It's encrypted and has a password. It won't cause any problem.

> Latest release also has the same problem.

It should be fine, I didn't touch output.

**Comment by sitiom** [comment] 2022-07-24 09:22
> Latest release also has the same problem.

I can confirm that the latest installer release has the same problem.

> updating it on winget requires some work that I'd do it only for each release.

Right, you should use the [Winget Releaser](https://bittu.eu.org/docs/wr-intro/) action to automate this.

**Comment by rollingmoai** [comment] 2022-07-24 10:13
> I can confirm that the latest installer release has the same problem.

Also chiming in, the latest installer has the same problem. I can't launch MFE when using the installer, but the portable zip works.

**Comment by xmine64** [comment] 2022-07-24 10:13
> I can confirm that the latest installer release has the same problem.

But `runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll` exits, weird.

> Right, you should use the [Winget Releaser](https://bittu.eu.org/docs/wr-intro/) action to automate it.

cool thanks

**Comment by piee-kun** [comment] 2022-07-24 15:24
If you're having issues with crashing when using the installer version, instead of saying "i also have this issue", it would be tons more useful to look in eventvwr and see what's actually crashing the program.

**Comment by sitiom** [comment] 2022-07-25 01:20
```
Description: A .NET Core application failed.
Application: MicaForEveryone.exe
Path: C:\Users\sitiom\AppData\Local\Programs\Mica For Everyone\MicaForEveryone.exe
Message: Error:
  An assembly specified in the application dependencies manifest (MicaForEveryone.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'
```

**Comment by xmine64** [comment] 2022-07-25 08:06
Ok I just realized what's wrong here. Inno copies runtimes folder content to root of installation target. Will be fixed soon.
![image](https://user-images.githubusercontent.com/21140798/180728757-0a517cf7-82fe-4ee9-8d79-ba6d04722bc7.png)

**Comment by itendtostare** [comment] 2022-08-05 10:35
same here for me ! Looking forward to the fix 

`Description:` A .NET Core application failed.
Application: MicaForEveryone.exe
Path: C:\Users\stare\AppData\Local\Programs\Mica For Everyone\MicaForEveryone.exe
Message: Error:
  An assembly specified in the application dependencies manifest (MicaForEveryone.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'``

**Comment by itendtostare** [comment] 2022-08-24 14:21
is there a different way to be able to use the program without the installer, as there has not been any fixes for this yet?

**Comment by dongle-the-gadget** [comment] 2022-08-24 14:22
Tbh I’m not really sure. I haven’t dealt with all of these kind of dependency bugs.

**Comment by xmine64** [comment] 2022-09-01 20:25
Is it still reproducible?

**Comment by dongle-the-gadget** [comment] 2022-09-02 12:51
Should be fixed.

**Closed by dongle-the-gadget** 2022-09-02 12:51 UTC
Labels: bug
